### PR TITLE
build: upgrade gradle 6.5 -> 8.2.1

### LINKED ISSUE #13: upgrade to gradle 6.9.x (prep for gradle 7.x)
Gradle 7 has some features Terasology is interested in (e.g. version catalogs). Since the MovingBlocks/✳ libraries are often used in composite builds with Terasology, it seems like a good idea to keep their gradle versions from drifting too far apart.

I propose upgrading all the libraries to the latest in the 6.x line (currently 6.9.0) and fixing whatever deprecation warnings crop up there. That should give us a smooth path to then adopting Gradle 7.

### PR DESCRIPTION
**Pull request by keturn**
Relates to https://github.com/MovingBlocks/Terasology/pull/5109
Relates to https://github.com/MovingBlocks/Terasology/pull/4653

### Contains

* Updating gradle from 6.5 -> 8.2.1
* Updating gradle's files for which became invalid

### How to test

* run `gradlew build` -> do we build JNBullet this way?
* we could further test it in combination with Terasology (`groovyw lib get JNBullet && gradlew jar game`)

### Remarks

Java 20 is not yet supported, see https://github.com/gradle/gradle/issues/23488.

Closes #13

### CODE REVIEW

**Comment by jdrueckert** [comment]
@pollend I updated this and I'm not sure whether the commit that updates swig-src files should be in here or whether we're missing something in our gitignore? The files just auto-updated when I ran `./gradlew tasks` :eyes:

**Comment by pollend** [comment]
I thought there was some scripts to generate the classes.i ?

**Comment by soloturn** [comment]
gradle-8.2.1 got released, better use that one?

**Comment by jdrueckert** [comment]
> did you try building it from cpp source?

@pollend nope didn't... should I try that or do you think building in the Terasology context (by including it in the libs dir) would work and be sufficient?

**Pull request merged**
